sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # look into default directory of sdk
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install and uodate kubectl in our environment, to set images on each deployment
  - gcloud components update kubectl
  # we authroize google sdk with a service account
  - gcloud auth activate-service-account --key-file service-account.json
