apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: notey-app-com-tls
spec:
  secretName: notey-app-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: notey-app.com
  dnsNames:
    - notey-app.com
    - www.notey-app.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - notey-app.com
          - www.notey-app.com