apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # tls:
  #   - hosts:
  #       - k8s-multi.com
  #       - www.k8s-multi.com
  #     secretName: k8s-multi-com
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: client-ip
              servicePort: 3000
          - path: /api
            backend:
              serviceName: server-ip
              servicePort: 5000