apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # it's reaching out to lets encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'mjd809@@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {} #we want to use the http-process of obtaining a cert, instead of dns option