apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: # lebels can be anything-- we can call compoent- "newstuff" and it will still work 
      component: server
  template: # is what our pods supposed to look like 
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: leojj/notey-server
          ports:
            - containerPort: 5000
          env:
            - name: MONGOURI #this val can be abything but our server is looking for pg password
              valueFrom:
                secretKeyRef:
                  name: mongouri
                  key: MONGOURI # secerets store key value pairs 